### ISSUE TITLE
Does Url::origin leak?

### ISSUE THREAD

**Issue by pratikpc** [ada-url/rust#63]
In [Url origin](https://github.com/ada-url/rust/blob/7cd8574cb01ed38b0b246fcf2c71d826efb0530d/src/lib.rs#L273), [ffi::ada_get_origin](https://github.com/ada-url/rust/blob/7cd8574cb01ed38b0b246fcf2c71d826efb0530d/src/ffi.rs#L75) is called

Within the C++ code, ada_get_origin allocates an [ada_owned_string](https://github.com/ada-url/rust/blob/7cd8574cb01ed38b0b246fcf2c71d826efb0530d/src/ffi.rs#L27) using [new[]](https://github.com/ada-url/ada/blob/e356ab9e8184ba1bb15a0d78a6c3af9a3e402761/src/ada_c.cpp#L122)

It is supposed to be freed using [ada_free_owned_string](https://github.com/ada-url/ada/blob/e356ab9e8184ba1bb15a0d78a6c3af9a3e402761/src/ada_c.cpp#L127).

However, the call to the function seems to be missing here.

**Comment by anonrig** [comment]
I think it leaks yes. Can you open a PR?

**Comment by pratikpc** [comment]
@anonrig sure but all changes required to fix this are potentially breaking changes (at least the ones I can think of) because they would require a breaking change of the return type

1. String.   
This would probably require creating a copy of the slice and then returning it and dropping the ada_owned_string
2. Returning ada_owned_string directly  
To ensure safe management of memory, possibly implement a drop function in ada_owned_string because it would be the RAII way.  
But that would be a breaking change for the user space as well because ada_owned_string is not dropped.

Both String and ada_owned_string are already convertible to str with as_str

Which approach would you prefer?

**Comment by anonrig** [comment]
We can store the reference to `ada_owned_string` in `URL` and still use RAII, without changing the API of course.

**Comment by pratikpc** [comment]
Hi

Would this approach involve storing the ada_owned_string returned by [ffi::ada_get_origin](https://github.com/ada-url/rust/blob/7cd8574cb01ed38b0b246fcf2c71d826efb0530d/src/ffi.rs#L75)?

If so, we would have to either use:-
1. Vector
2. Option

In case a user can mutate the origin, so multiple calls are capable of returning different values, then in this case Vector is the best approach.

Otherwise, we could use Option as only a single value would be needed.

The approach while memory does sound a bit weird though no?

Or am I a bit confused?

**Comment by anonrig** [comment]
I'm fine with both options. I can release a new major
